exports.NOT_FOUND_ERR = 'NOT_FOUND_ERR';
exports.CLIENT_ERR = 'CLIENT_ERR';
exports.TOKEN_ERR = 'TOKEN_ERR';
exports.TOKEN_EXPIRED_ERR = 'TOKEN_EXPIRED_ERR';
exports.AUTHENTICATION_ERR = 'AUTHENTICATION_ERR';
exports.AUTHORIZATION_ERR = 'AUTHORIZATION_ERR';
exports.CONFLICT_ERR = 'CONFLICT_ERR';
exports.SERVER_ERR = 'SERVER_ERR';
